Repository plone/plone.restapi, pull requests merged in 2018-06, with the labels that each got.

#533 Hide upgrade profile from add-ons control panel in 5.1
  CHANGES.rst
  src/plone/restapi/setuphandlers.py
  versions.cfg
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review

#540 Translate the fti title in @types endpoint
  CHANGES.rst
  src/plone/restapi/services/types/get.py
  src/plone/restapi/tests/test_services_types.py
Labels: 24 status: ready

#555 Make sure DX DefaultFieldDeserializer validates field values.
  CHANGES.rst
  src/plone/restapi/deserializer/dxfields.py
  src/plone/restapi/tests/test_dxfield_deserializer.py
Labels: 23 status: testing

#554 Have tests fail on Sphinx documentation errors / warnings
  .travis.yml
  base.cfg
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/roles.rst
  docs/source/sharing.rst
  test-no-sphinx-warnings.in
Labels: 04 type: enhancement, 23 status: testing

#541 Translate workflow history titles
  CHANGES.rst
  src/plone/restapi/services/history/get.py
  src/plone/restapi/tests/test_services_history.py
Labels: 24 status: ready

#559 Include translated role titles in `@sharing` GET
  CHANGES.rst
  docs/source/_json/sharing_folder_get.resp
  docs/source/_json/sharing_folder_get_include_titles.req
  docs/source/_json/sharing_folder_post.req
  docs/source/_json/sharing_search.resp
  docs/source/sharing.rst
  docs/source/upgrade-guide.rst
  src/plone/restapi/serializer/local_roles.py
  src/plone/restapi/services/content/sharing.py
  src/plone/restapi/tests/test_content_local_roles.py
  src/plone/restapi/tests/test_documentation.py
Labels: 23 status: testing

#553 Create image URLs using the cache optimized URLs
  CHANGES.rst
  docs/source/_json/image.resp
  docs/source/_json/newsitem.resp
  docs/source/plone-content.rst
  docs/source/serialization.rst
  docs/source/upgrade-guide.rst
  setup.py
  src/plone/restapi/imaging.py
  src/plone/restapi/serializer/atfields.py
  src/plone/restapi/serializer/dxfields.py
  src/plone/restapi/tests/test_atfield_serializer.py
  src/plone/restapi/tests/test_documentation.py
  src/plone/restapi/tests/test_dxfield_serializer.py
  src/plone/restapi/tests/test_serializer.py
  src/plone/restapi/tests/test_services.py
Labels: 24 status: ready, 32 needs: review

#568 Properly include HTTP examples in installed egg
  CHANGES.rst
  setup.py
  src/plone/restapi/tests/test_documentation.py
Labels: 24 status: ready, 32 needs: review
