Repository plone/plone.restapi, pull requests merged in 2018-04, with the labels that each got.

#523 Improve the navigation endpoint by being able to return the items nav…
  CHANGES.rst
  docs/source/_json/expansion_expanded_full.resp
  docs/source/_json/navigation.resp
  docs/source/_json/navigation_tree.req
  docs/source/_json/navigation_tree.resp
  docs/source/navigation.rst
  src/plone/restapi/services/navigation/get.py
  src/plone/restapi/tests/test_documentation.py
  src/plone/restapi/tests/test_expansion.py
  src/plone/restapi/tests/test_services_navigation.py
  versions.cfg
Labels: in progress

#490 Expandable translations
  CHANGES.rst
  docs/source/_json/translations_get.resp
  docs/source/expansion.rst
  docs/source/translations.rst
  docs/source/upgrade-guide.rst
  src/plone/restapi/services/multilingual/configure.zcml
  src/plone/restapi/services/multilingual/pam.py
  src/plone/restapi/tests/test_expansion.py
  src/plone/restapi/tests/test_translations.py
Labels: 04 type: enhancement, 24 status: ready

#516 Expose widgets tagged values via @types endpoint
  CHANGES.rst
  docs/source/_json/types_document.resp
  docs/source/types.rst
  src/plone/restapi/tests/test_types.py
  src/plone/restapi/types/adapters.py
  src/plone/restapi/types/configure.zcml
  src/plone/restapi/types/utils.py
Labels: 04 type: enhancement

#493 convert date/times to UTC when exporting, use python-datetime for parsing date strings
  CHANGES.rst
  setup.py
  src/plone/restapi/deserializer/dxfields.py
  src/plone/restapi/serializer/converters.py
  src/plone/restapi/testing.py
  src/plone/restapi/tests/test_serializer_converters.py
Labels: 04 type: enhancement, 12 prio: high, 23 status: testing

#525 New permission for accessing user information in the GET @user endpoint...
  CHANGES.rst
  src/plone/restapi/permissions.zcml
  src/plone/restapi/profiles/default/metadata.xml
  src/plone/restapi/profiles/default/rolemap.xml
  src/plone/restapi/services/users/get.py
  src/plone/restapi/tests/test_upgrades.py
  src/plone/restapi/upgrades/configure.zcml
  src/plone/restapi/upgrades/profiles/0004/rolemap.xml
  src/plone/restapi/upgrades/to0004.py
Labels: in progress
