Repository plone/plone.restapi, pull requests merged in 2019-12, with the labels that each got.

#839 Rename iface name to the short name in blocks
  news/838.bugfix
  src/plone/restapi/profiles/blocks/types/Document.xml
  src/plone/restapi/profiles/default/metadata.xml
  src/plone/restapi/tests/test_behaviors.py
  src/plone/restapi/tests/test_content_blocks.py
  src/plone/restapi/upgrades/configure.zcml
  src/plone/restapi/upgrades/to0005.py
  src/plone/restapi/upgrades/to0006.py
Labels: 01 type: bug, 12 prio: high, 24 status: ready, 51 target: patch

#828 Prevent converting bytestring ids to unicode ids when reordering on python2.
  docs/source/upgrade-guide.rst
  news/827.bugfix
  src/plone/restapi/deserializer/mixins.py
  src/plone/restapi/tests/mixin_ordering.py
  src/plone/restapi/tests/test_upgrade_ordering.py
  src/plone/restapi/upgrades/configure.zcml
  src/plone/restapi/upgrades/ordering.py
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#819 Remove IAPIRequest marker interface
  news/819.bugfix
  src/plone/restapi/interfaces.py
Labels: 04 type: enhancement, 14 prio: low, 53 target: major
