Repository plone/plone.restapi, pull requests merged in 2020-03, with the labels that each got.

#872 Allow objects paths and UIDs to link translations.
  docs/source/translations.rst
  news/645.feature
  src/plone/restapi/services/multilingual/pam.py
  src/plone/restapi/tests/http-examples/translations_post_by_id.req
  src/plone/restapi/tests/http-examples/translations_post_by_id.resp
  src/plone/restapi/tests/http-examples/translations_post_by_uid.req
  src/plone/restapi/tests/http-examples/translations_post_by_uid.resp
  src/plone/restapi/tests/test_documentation.py
  src/plone/restapi/tests/test_translations.py
Labels: 04 type: enhancement, 24 status: ready

#879 Fixed package install error with Python 3.6 without locale.
  news/642.bugfix
  setup.py
Labels: 02 type: regression, 13 prio: normal, 23 status: testing, 32 needs: review

#820 Resolve paths to UIDs
  news/808.feature
  plone-4.3.x.cfg
  src/plone/restapi/deserializer/blocks.py
  src/plone/restapi/deserializer/configure.zcml
  src/plone/restapi/serializer/blocks.py
  src/plone/restapi/serializer/configure.zcml
  src/plone/restapi/tests/test_resolveuid.py
  src/plone/restapi/tests/test_resolveuid_functional.py
Labels: 23 status: testing, 31 needs: help
