Repository plone/plone.restapi, pull requests merged in 2020-09, with the labels that each got.

#988 Fixed deprecation warnings for zope.site.hooks and ILanguageSchema.
  news/975.bugfix
  src/plone/restapi/testing.py
  src/plone/restapi/tests/test_documentation.py
  src/plone/restapi/tests/test_serializer_summary.py
  src/plone/restapi/types/utils.py
Labels: 01 type: bug, 14 prio: low, 23 status: testing, 32 needs: review

#985 Control Panels Plone 4 support
  news/984.feature
  src/plone/restapi/controlpanels/__init__.py
  src/plone/restapi/controlpanels/registry.py
  src/plone/restapi/controlpanels/types.py
  src/plone/restapi/deserializer/configure.zcml
  src/plone/restapi/serializer/configure.zcml
  src/plone/restapi/services/configure.zcml
  src/plone/restapi/services/controlpanels/configure.zcml
  src/plone/restapi/tests/test_services_controlpanel_dexterity_types.py
Labels: 24 status: ready

#992 Pin pyrsistent to 0.15.7 in buildout configs.
  plone-4.3.x.cfg
  plone-5.0.x.cfg
  plone-5.1.x.cfg
Labels: 02 type: regression, 11 prio: blocker, 23 status: testing, 32 needs: review

#876 Remove uneeded stringtype checks
  news/875.feature
  src/plone/restapi/services/copymove/copymove.py
  src/plone/restapi/services/multilingual/pam.py
Labels: 04 type: enhancement, 24 status: ready

#991 Fix tests with Products.MailHost 4.10.
  news/3178.bugfix
  src/plone/restapi/tests/test_services_email_notification.py
  src/plone/restapi/tests/test_services_email_send.py
  src/plone/restapi/tests/test_services_users.py
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review
