Repository plone/plone.restapi, pull requests merged in 2021-11, with the labels that each got.

#1267 Remove all traces of Products.CMFQuickInstaller
  news/1267.bugfix
  src/plone/restapi/services/addons/addons.py
Labels: 01 type: bug, 23 status: testing, 12 prio: high

#1269 fix: pas plugin was missing after install
  news/1269.bugfix
  src/plone/restapi/configure.zcml
  src/plone/restapi/profiles/default/plone.restapi_various.txt
  src/plone/restapi/setuphandlers.py
Labels: 01 type: bug, 22 status: in-progress, 12 prio: high, 52 target: minor

#1272 Fix schema generation when /@types/ is used in a context
  news/1271.bugfix
  src/plone/restapi/tests/http-examples/translated_messages_types_folder.resp
  src/plone/restapi/tests/http-examples/types_document.resp
  src/plone/restapi/tests/http-examples/types_document_put.req
  src/plone/restapi/types/utils.py
Labels: 01 type: bug
