Repository plone/plone.restapi, pull requests merged in 2021-09, with the labels that each got.

#1221 @users endpoint should use acl_users.searchUsers.
  news/1199.bugfix
  src/plone/restapi/services/users/get.py
Labels: 01 type: bug

#1229 @types endpoint: Return if a type is immediately addable in the context
  news/1228.feature
  src/plone/restapi/services/types/get.py
  src/plone/restapi/tests/http-examples/expansion_expanded_full.resp
  src/plone/restapi/tests/http-examples/translated_messages_types.resp
  src/plone/restapi/tests/http-examples/types.resp
  src/plone/restapi/tests/test_expansion.py
  src/plone/restapi/tests/test_services_types.py
Labels: 04 type: enhancement

#1226 Further normalise http-examples, and no port hardcoding
  base.cfg
  news/1226.bugfix
  src/plone/restapi/tests/http-examples/types_document.resp
  src/plone/restapi/tests/http-examples/types_document_get_field.resp
  src/plone/restapi/tests/http-examples/types_document_post_field.resp
  src/plone/restapi/tests/http-examples/types_document_put.req
  src/plone/restapi/tests/test_documentation.py
Labels: 32 needs: review, 23 status: testing, 04 type: enhancement, 13 prio: normal
