Repository plone/plone.restapi, pull requests merged in 2021-07, with the labels that each got.

#1155 Use security decorators in PAS plugin.
  news/1155.bugfix
  src/plone/restapi/pas/plugin.py
Labels: 04 type: enhancement, 14 prio: low, 23 status: testing

#1158 Eliminate non-pythonic 'return None' usage
  news/1158.bugfix
  src/plone/restapi/batching.py
  src/plone/restapi/deserializer/mixins.py
  src/plone/restapi/imaging.py
  src/plone/restapi/indexers.py
  src/plone/restapi/pas/plugin.py
  src/plone/restapi/serializer/converters.py
  src/plone/restapi/serializer/discussion.py
  src/plone/restapi/serializer/dxfields.py
  src/plone/restapi/services/addons/post.py
  src/plone/restapi/services/auth/login.py
  src/plone/restapi/services/content/tus.py
  src/plone/restapi/services/contextnavigation/get.py
  src/plone/restapi/types/adapters.py
Labels: 04 type: enhancement, 14 prio: low, 23 status: testing

#1157 Fix PAS plugin markup for Zope4+
  news/1157.bugfix
  src/plone/restapi/pas/add_plugin.zpt
  src/plone/restapi/pas/config.zpt
Labels: 02 type: regression, 13 prio: normal, 23 status: testing

#1166 Fix startup on Plone 4 without plone.app.contenttypes.
  news/1166.bugfix
  src/plone/restapi/deserializer/configure.zcml
  src/plone/restapi/deserializer/dxfields.py
  src/plone/restapi/serializer/configure.zcml
  src/plone/restapi/serializer/dxfields.py
Labels: 02 type: regression, 13 prio: normal, 24 status: ready, 32 needs: review

#1173 Set UID of a content during creation
  docs/source/content.rst
  news/497.feature
  src/plone/restapi/services/content/add.py
  src/plone/restapi/tests/test_content_post.py
Labels: 04 type: enhancement, 24 status: ready
