Repository plone/plone.restapi, pull requests merged in 2022-10, with the labels that each got.

#1523 Add link integrity support for slate blocks
  news/1522.feature
  src/plone/restapi/blocks_linkintegrity.py
  src/plone/restapi/configure.zcml
  src/plone/restapi/tests/test_blocks_linkintegrity.py
Labels: 11 prio: blocker

#1524 Fix portrait endpoint for email address user id's
  news/1524.bugfix
  src/plone/restapi/serializer/discussion.py
  src/plone/restapi/serializer/user.py
  src/plone/restapi/services/users/get.py
  src/plone/restapi/tests/http-examples/translated_messages_addons.resp
  src/plone/restapi/tests/test_comments.py
  src/plone/restapi/tests/test_services_users.py
Labels: 01 type: bug

#1520 Fix test_statictime for p.a.discussion comments
  news/1520.bugfix
  src/plone/restapi/tests/test_statictime.py
Labels: 01 type: bug, 23 status: testing, 12 prio: high
