Repository plone/plone.restapi, pull requests merged in 2022-08, with the labels that each got.

#1460 Fix of users endpoint for Membrane users.
  docs/source/conf.py
  news/1459.bugfix
  src/plone/restapi/services/users/get.py
  src/plone/restapi/tests/http-examples/translated_messages_addons.resp
Labels: 12 prio: high

#1466 Use _getsafeMemberId when checking for user portrait
  CONTRIBUTORS.rst
  news/1466.bugfix
  src/plone/restapi/serializer/user.py
Labels: 01 type: bug

#1461 fix: plone.restapi must work with dependency on only Products.CMFPlone
  news/1461.bugfix
  src/plone/restapi/serializer/dxcontent.py
  src/plone/restapi/services/configure.zcml
Labels: 01 type: bug, 23 status: testing, 12 prio: high
