Repository plone/plone.restapi, pull requests merged in 2023-08, with the labels that each got.

#1599 Allow passing additional parameters to the @users endpoint when deleting a user
  docs/source/endpoints/users.md
  news/1598.feat
  src/plone/restapi/services/users/delete.py
  src/plone/restapi/tests/http-examples/users_delete_no_localroles.req
  src/plone/restapi/tests/http-examples/users_delete_no_localroles.resp
  src/plone/restapi/tests/http-examples/users_delete_no_memberareas.req
  src/plone/restapi/tests/http-examples/users_delete_no_memberareas.resp
  src/plone/restapi/tests/test_documentation.py
  src/plone/restapi/tests/test_services_users.py
Labels: 24 status: ready

#1570 Use incoming request to produce location for @tus-upload
  news/1570.bugfix
  src/plone/restapi/services/content/tus.py
  src/plone/restapi/tests/test_tus.py
Labels: 01 type: bug, 24 status: ready

#1688 Remove plone.tiles and the `@tiles` endpoint
  docs/source/endpoints/index.md
  docs/source/endpoints/tiles.md
  docs/source/upgrade-guide.md
  news/1308.breaking
  setup.py
  src/plone/restapi/serializer/configure.zcml
  src/plone/restapi/serializer/tile.py
  src/plone/restapi/services/configure.zcml
  src/plone/restapi/services/tiles/__init__.py
  src/plone/restapi/services/tiles/configure.zcml
  src/plone/restapi/services/tiles/get.py
  src/plone/restapi/tests/test_services_tiles.py
Labels: 22 status: in-progress

#1235 [9.x.x] - Remove deprecated @unlock, @refresh-lock endpoints
  docs/source/endpoints/locking.md
  docs/source/upgrade-guide.md
  news/1235.breaking
  src/plone/restapi/services/locking/configure.zcml
  src/plone/restapi/services/locking/locking.py
Labels: 53 target: major
